<?php

namespace Database\Seeders;

use App\Models\PageMultipleFieldData;
use Illuminate\Database\Seeder;

class PageMultipleFieldDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        PageMultipleFieldData::insert([
            [
                'id' => 1,
                'name' => 'Título',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 1,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-10 20:09:55',
            ],
            [
                'id' => 2,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 3,
                'page_multiple_field_id' => 1,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-10 20:09:55',
            ],
            [
                'id' => 3,
                'name' => 'Imagen responsive',
                'variable' => 'imagen_responsive',
                'index' => 4,
                'page_multiple_field_id' => 1,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-10 20:09:55',
            ],
            [
                'id' => 4,
                'name' => 'Título',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 2,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 5,
                'name' => 'Dirección',
                'variable' => 'direccion',
                'index' => 2,
                'page_multiple_field_id' => 2,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 6,
                'name' => 'Horario',
                'variable' => 'horario',
                'index' => 3,
                'page_multiple_field_id' => 2,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 7,
                'name' => 'Teléfono',
                'variable' => 'telefono',
                'index' => 4,
                'page_multiple_field_id' => 2,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 8,
                'name' => 'Código de ubigeo',
                'variable' => 'codigo_ubigeo',
                'index' => 5,
                'page_multiple_field_id' => 2,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 9,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 3,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 10,
                'name' => 'Icono',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 3,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-11 17:25:02',
            ],
            [
                'id' => 11,
                'name' => 'Título',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 4,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-18 21:03:32',
            ],
            [
                'id' => 12,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 2,
                'page_multiple_field_id' => 4,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-18 21:03:32',
            ],
            [
                'id' => 13,
                'name' => 'Imagen de fondo',
                'variable' => 'imagen_fondo',
                'index' => 3,
                'page_multiple_field_id' => 4,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-18 21:03:32',
            ],
            [
                'id' => 14,
                'name' => 'Título',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 5,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-19 07:24:15',
            ],
            [
                'id' => 15,
                'name' => 'Ubicación',
                'variable' => 'ubicacion',
                'index' => 2,
                'page_multiple_field_id' => 5,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 16,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 3,
                'page_multiple_field_id' => 5,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-19 07:24:25',
            ],
            [
                'id' => 17,
                'name' => 'Imagen de usuario',
                'variable' => 'imagen_usuario',
                'index' => 4,
                'page_multiple_field_id' => 5,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 18,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 6,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 19,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 6,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-01-07 21:12:25',
            ],
            [
                'id' => 20,
                'name' => 'Título',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 21,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 7,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 22,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 2,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 23,
                'name' => 'Texto de acordeón',
                'variable' => 'texto_acordeon',
                'index' => 3,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 24,
                'name' => 'Texto de fecha de promoción',
                'variable' => 'texto_fecha_promocion',
                'index' => 4,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 25,
                'name' => 'Lista de términos y condiciones',
                'variable' => 'lista_terminos_condiciones',
                'index' => 5,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-07 21:12:25',
                'updated_at' => '2025-02-10 22:50:21',
            ],
            [
                'id' => 26,
                'name' => 'SubTitulo',
                'variable' => 'subTitle',
                'index' => 2,
                'page_multiple_field_id' => 1,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-10 20:09:26',
                'updated_at' => '2025-01-10 20:09:55',
            ],
            [
                'id' => 27,
                'name' => 'Icono activo',
                'variable' => 'imagen_active',
                'index' => 3,
                'page_multiple_field_id' => 3,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-11 17:24:54',
                'updated_at' => '2025-01-15 04:13:32',
            ],
            [
                'id' => 28,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 9,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-15 20:59:55',
                'updated_at' => '2025-01-18 22:09:52',
            ],
            [
                'id' => 29,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 3,
                'page_multiple_field_id' => 9,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-15 21:00:08',
                'updated_at' => '2025-01-18 22:08:29',
            ],
            [
                'id' => 30,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 10,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-15 21:13:35',
                'updated_at' => '2025-01-15 21:13:35',
            ],
            [
                'id' => 31,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 10,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-15 21:13:44',
                'updated_at' => '2025-01-15 21:13:44',
            ],
            [
                'id' => 32,
                'name' => 'Icono',
                'variable' => 'icon',
                'index' => 4,
                'page_multiple_field_id' => 4,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-18 21:03:26',
                'updated_at' => '2025-01-18 21:03:32',
            ],
            [
                'id' => 34,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 11,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 05:57:44',
                'updated_at' => '2025-01-19 05:57:44',
            ],
            [
                'id' => 35,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 11,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 05:58:05',
                'updated_at' => '2025-01-19 05:58:05',
            ],
            [
                'id' => 36,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 12,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 05:58:13',
                'updated_at' => '2025-01-19 05:58:13',
            ],
            [
                'id' => 37,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 12,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 05:58:19',
                'updated_at' => '2025-01-19 05:58:19',
            ],
            [
                'id' => 38,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 13,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 05:58:29',
                'updated_at' => '2025-01-19 05:58:29',
            ],
            [
                'id' => 39,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 13,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 05:58:34',
                'updated_at' => '2025-01-19 06:02:51',
            ],
            [
                'id' => 40,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 14,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 06:02:39',
                'updated_at' => '2025-01-19 06:02:39',
            ],
            [
                'id' => 41,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 14,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 06:02:45',
                'updated_at' => '2025-01-19 06:02:45',
            ],
            [
                'id' => 42,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 15,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 06:04:48',
                'updated_at' => '2025-01-19 06:04:48',
            ],
            [
                'id' => 43,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 15,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 06:04:53',
                'updated_at' => '2025-01-19 06:04:53',
            ],
            [
                'id' => 44,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 1,
                'page_multiple_field_id' => 16,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-19 06:06:03',
                'updated_at' => '2025-01-19 06:06:03',
            ],
            [
                'id' => 45,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 16,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 06:06:09',
                'updated_at' => '2025-01-19 06:06:09',
            ],
            [
                'id' => 46,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 3,
                'page_multiple_field_id' => 17,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-19 06:07:00',
                'updated_at' => '2025-01-21 18:02:51',
            ],
            [
                'id' => 47,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 2,
                'page_multiple_field_id' => 17,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-19 06:07:06',
                'updated_at' => '2025-01-21 18:02:51',
            ],
            [
                'id' => 48,
                'name' => 'Titulo',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 18,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:50:49',
                'updated_at' => '2025-01-20 20:50:49',
            ],
            [
                'id' => 49,
                'name' => 'Dirección',
                'variable' => 'direccion',
                'index' => 2,
                'page_multiple_field_id' => 18,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:51:10',
                'updated_at' => '2025-01-20 20:51:10',
            ],
            [
                'id' => 50,
                'name' => 'Horario',
                'variable' => 'horario',
                'index' => 3,
                'page_multiple_field_id' => 18,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:51:19',
                'updated_at' => '2025-01-20 20:51:19',
            ],
            [
                'id' => 51,
                'name' => 'Teléfono',
                'variable' => 'telefono',
                'index' => 4,
                'page_multiple_field_id' => 18,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:51:43',
                'updated_at' => '2025-01-20 20:51:43',
            ],
            [
                'id' => 52,
                'name' => 'Código de ubigeo',
                'variable' => 'codigo_ubigeo',
                'index' => 5,
                'page_multiple_field_id' => 18,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:51:54',
                'updated_at' => '2025-01-20 20:51:54',
            ],
            [
                'id' => 53,
                'name' => 'Titulo',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 19,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:53:24',
                'updated_at' => '2025-01-20 20:53:24',
            ],
            [
                'id' => 54,
                'name' => 'Dirección',
                'variable' => 'direccion',
                'index' => 2,
                'page_multiple_field_id' => 19,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:53:43',
                'updated_at' => '2025-01-20 20:53:43',
            ],
            [
                'id' => 55,
                'name' => 'Horario',
                'variable' => 'horario',
                'index' => 3,
                'page_multiple_field_id' => 19,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:53:51',
                'updated_at' => '2025-01-20 20:53:51',
            ],
            [
                'id' => 56,
                'name' => 'Teléfono',
                'variable' => 'telefono',
                'index' => 4,
                'page_multiple_field_id' => 19,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:54:00',
                'updated_at' => '2025-01-20 20:54:00',
            ],
            [
                'id' => 57,
                'name' => 'Código de ubigeo',
                'variable' => 'codigo_ubigeo',
                'index' => 5,
                'page_multiple_field_id' => 19,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 20:54:09',
                'updated_at' => '2025-01-20 20:54:09',
            ],
            [
                'id' => 58,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 1,
                'page_multiple_field_id' => 21,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 21:39:10',
                'updated_at' => '2025-01-20 21:39:10',
            ],
            [
                'id' => 59,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 1,
                'page_multiple_field_id' => 22,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 21:40:32',
                'updated_at' => '2025-01-20 21:40:32',
            ],
            [
                'id' => 60,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 1,
                'page_multiple_field_id' => 23,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 21:40:39',
                'updated_at' => '2025-01-20 21:40:39',
            ],
            [
                'id' => 61,
                'name' => 'Titulo azul',
                'variable' => 'titulo_azul',
                'index' => 1,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:10:38',
                'updated_at' => '2025-01-20 22:10:38',
            ],
            [
                'id' => 62,
                'name' => 'Titulo naranja',
                'variable' => 'titulo_naranja',
                'index' => 2,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:10:51',
                'updated_at' => '2025-01-20 22:10:51',
            ],
            [
                'id' => 63,
                'name' => 'Logo',
                'variable' => 'logo',
                'index' => 3,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:11:12',
                'updated_at' => '2025-01-20 22:11:16',
            ],
            [
                'id' => 64,
                'name' => 'Descripción',
                'variable' => 'descripcion',
                'index' => 4,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 2,
                'created_at' => '2025-01-20 22:11:25',
                'updated_at' => '2025-01-20 22:11:25',
            ],
            [
                'id' => 65,
                'name' => 'N° horas',
                'variable' => 'numero_horas',
                'index' => 5,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:11:39',
                'updated_at' => '2025-01-20 22:11:39',
            ],
            [
                'id' => 66,
                'name' => 'Texto horas',
                'variable' => 'texto_horas',
                'index' => 6,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:11:53',
                'updated_at' => '2025-01-20 22:11:53',
            ],
            [
                'id' => 67,
                'name' => 'Icono horas',
                'variable' => 'icono_horas',
                'index' => 7,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:12:07',
                'updated_at' => '2025-01-20 22:12:07',
            ],
            [
                'id' => 68,
                'name' => 'N° beneficiados',
                'variable' => 'numero_beneficiados',
                'index' => 8,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:12:28',
                'updated_at' => '2025-01-20 22:12:28',
            ],
            [
                'id' => 69,
                'name' => 'Texto beneficiados',
                'variable' => 'texto_beneficiados',
                'index' => 9,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:12:37',
                'updated_at' => '2025-01-20 22:12:37',
            ],
            [
                'id' => 70,
                'name' => 'Icono beneficiados',
                'variable' => 'icono_beneficiados',
                'index' => 10,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:12:48',
                'updated_at' => '2025-01-20 22:12:48',
            ],
            [
                'id' => 71,
                'name' => 'N° alianzas',
                'variable' => 'numero_alianzas',
                'index' => 11,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:12:59',
                'updated_at' => '2025-01-20 22:12:59',
            ],
            [
                'id' => 72,
                'name' => 'Texto alianzas',
                'variable' => 'texto_alianzas',
                'index' => 12,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:13:09',
                'updated_at' => '2025-01-20 22:13:09',
            ],
            [
                'id' => 73,
                'name' => 'Icono alianzas',
                'variable' => 'icono_alianzas',
                'index' => 13,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:13:19',
                'updated_at' => '2025-01-20 22:13:19',
            ],
            [
                'id' => 74,
                'name' => 'N° conectados',
                'variable' => 'numero_conectados',
                'index' => 14,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:13:30',
                'updated_at' => '2025-01-20 22:13:30',
            ],
            [
                'id' => 75,
                'name' => 'Texto conectados',
                'variable' => 'texto_conectados',
                'index' => 15,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:13:43',
                'updated_at' => '2025-01-20 22:13:43',
            ],
            [
                'id' => 76,
                'name' => 'Icono conectados',
                'variable' => 'icono_conectados',
                'index' => 16,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:14:00',
                'updated_at' => '2025-01-20 22:14:00',
            ],
            [
                'id' => 77,
                'name' => 'Imagen',
                'variable' => 'imagen',
                'index' => 17,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-20 22:14:09',
                'updated_at' => '2025-01-20 22:14:09',
            ],
            [
                'id' => 78,
                'name' => 'Texto imagen',
                'variable' => 'texto_imagen',
                'index' => 18,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:14:23',
                'updated_at' => '2025-01-20 22:14:23',
            ],
            [
                'id' => 79,
                'name' => 'Texto botón',
                'variable' => 'texto_boton',
                'index' => 19,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:14:30',
                'updated_at' => '2025-01-20 22:14:30',
            ],
            [
                'id' => 80,
                'name' => 'Enlace botón',
                'variable' => 'enlace_boton',
                'index' => 20,
                'page_multiple_field_id' => 24,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-20 22:14:36',
                'updated_at' => '2025-01-20 22:14:36',
            ],
            [
                'id' => 81,
                'name' => 'Título',
                'variable' => 'title',
                'index' => 1,
                'page_multiple_field_id' => 17,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-21 17:53:45',
                'updated_at' => '2025-01-21 18:02:51',
            ],
            [
                'id' => 83,
                'name' => 'Titulo',
                'variable' => 'titulo',
                'index' => 1,
                'page_multiple_field_id' => 25,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-27 17:42:32',
                'updated_at' => '2025-02-10 13:30:44',
            ],
            [
                'id' => 84,
                'name' => 'Documento',
                'variable' => 'documento',
                'index' => 2,
                'page_multiple_field_id' => 25,
                'page_field_type_id' => 5,
                'created_at' => '2025-01-27 21:55:08',
                'updated_at' => '2025-02-10 13:30:44',
            ],
            [
                'id' => 85,
                'name' => 'Código de ubigeo',
                'variable' => 'codigo_ubigeo',
                'index' => 6,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 1,
                'created_at' => '2025-01-28 06:20:44',
                'updated_at' => '2025-02-10 22:53:38',
            ],
            [
                'id' => 86,
                'name' => 'Imagen responsive',
                'variable' => 'imagen_responsive',
                'index' => 8,
                'page_multiple_field_id' => 7,
                'page_field_type_id' => 3,
                'created_at' => '2025-01-28 06:24:09',
                'updated_at' => '2025-02-10 22:50:21',
            ],
        ]);
    }
}
