version: "3.8"
services:
    laravel-app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: webapi-laravel
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - solgas

    nginx:
        image: nginx:alpine
        container_name: webapi-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel-app
        networks:
            - solgas

    mysql:
        image: mysql:8
        container_name: webapi-mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
        ports:
            - "3306:3306"
        networks:
            - solgas

volumes:
    mysql-data:

networks:
    solgas:
        driver: bridge
